vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
        gameLogo:
            uri_prefix: /images/games/logos
            upload_destination: '%kernel.project_dir%/public/images/games/logos'